# Generated by Django 4.1.6 on 2023-03-06 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='parol',
            new_name='lavozim',
        ),
        migrations.RemoveField(
            model_name='user',
            name='arm',
        ),
        migrations.RemoveField(
            model_name='user',
            name='talaba',
        ),
    ]
