# Generated by Django 4.1.6 on 2023-03-06 09:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_parol_user_lavozim_remove_user_arm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dekanat',
        ),
        migrations.AddField(
            model_name='user',
            name='parol',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
