# Generated by Django 4.1.7 on 2023-03-24 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_dekanat_user_parol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='kocha',
        ),
        migrations.RemoveField(
            model_name='user',
            name='shahar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='viloyat',
        ),
    ]
