# Generated by Django 4.1.7 on 2023-03-25 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_kocha_remove_user_shahar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kocha',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='shahar',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='viloyat',
            field=models.CharField(default=11, max_length=200),
            preserve_default=False,
        ),
    ]
