# Generated by Django 4.2 on 2023-04-09 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_kocha_user_shahar_user_viloyat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lavozim',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
