# Generated by Django 4.2 on 2023-04-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_lavozim'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='talaba_kafaedra',
            new_name='talaba_kurs',
        ),
        migrations.AddField(
            model_name='user',
            name='talaba_yonalish',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
