# Generated by Django 4.2 on 2023-04-09 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_talaba_kafaedra_user_talaba_kurs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='lavozim',
        ),
    ]
