# Generated by Django 4.2 on 2023-04-09 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_user_lavozim'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lavozim',
            field=models.CharField(default='talaba', max_length=100),
        ),
    ]
