# Generated by Django 4.2 on 2023-04-09 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_lavozim'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='arm',
            field=models.BooleanField(default=False, max_length=100),
        ),
    ]
