# Generated by Django 4.2 on 2023-04-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_user_lavozim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lavozim',
            field=models.CharField(max_length=100),
        ),
    ]
