# Generated by Django 4.1.7 on 2023-03-25 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fakultet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fakultet', models.CharField(max_length=100)),
                ('sana', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Yonalish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yonalish', models.CharField(max_length=100)),
                ('sana', models.DateTimeField(auto_now_add=True)),
                ('fakultet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talaba.fakultet')),
            ],
        ),
        migrations.CreateModel(
            name='Kurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kurs', models.CharField(max_length=10)),
                ('sana', models.DateTimeField(auto_now_add=True)),
                ('fakultet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talaba.fakultet')),
                ('yonalish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talaba.yonalish')),
            ],
        ),
        migrations.CreateModel(
            name='Kafedra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kafedra', models.CharField(max_length=100)),
                ('sana', models.DateTimeField(auto_now_add=True)),
                ('fakultet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talaba.fakultet')),
            ],
        ),
        migrations.CreateModel(
            name='Guruh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guruh', models.CharField(max_length=10)),
                ('sana', models.DateTimeField(auto_now_add=True)),
                ('fakultet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talaba.fakultet')),
                ('kurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talaba.kurs')),
                ('yonalish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talaba.yonalish')),
            ],
        ),
    ]
