# Generated by Django 4.2 on 2023-05-02 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talaba', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Talaba_activ',
        ),
    ]
