# Generated by Django 4.1.7 on 2023-03-25 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talaba', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viloyat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viloyat', models.CharField(max_length=100)),
                ('sana', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tuman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tuman', models.CharField(max_length=100)),
                ('sana', models.DateTimeField(auto_now_add=True)),
                ('vilyat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talaba.viloyat')),
            ],
        ),
        migrations.CreateModel(
            name='Mfy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mfy', models.CharField(max_length=100)),
                ('sana', models.DateTimeField(auto_now_add=True)),
                ('tuman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talaba.tuman')),
                ('viloyat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talaba.viloyat')),
            ],
        ),
    ]
