# Generated by Django 4.2 on 2023-05-02 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('arm', '0014_alter_kitoblar_mundarija'),
        ('talaba', '0002_delete_talaba_activ'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talaba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kitoblar_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arm.kitoblar')),
                ('talabalat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arm.talabalar')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
