# Generated by Django 4.1.7 on 2023-03-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talaba', '0002_viloyat_tuman_mfy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mfy',
            name='tuman',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mfy',
            name='viloyat',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tuman',
            name='vilyat',
            field=models.CharField(max_length=100),
        ),
    ]
