# Generated by Django 4.1.7 on 2023-03-25 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talaba', '0003_alter_mfy_tuman_alter_mfy_viloyat_alter_tuman_vilyat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tuman',
            old_name='vilyat',
            new_name='viloyat',
        ),
    ]
