# Generated by Django 4.1.7 on 2023-03-25 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talaba', '0004_rename_vilyat_tuman_viloyat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuman',
            name='viloyat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talaba.viloyat'),
        ),
    ]
