# Generated by Django 4.1.7 on 2023-03-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talaba', '0005_alter_tuman_viloyat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuman',
            name='viloyat',
            field=models.CharField(max_length=100),
        ),
    ]
