# Generated by Django 4.2 on 2023-04-07 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talaba', '0009_alter_kafedra_fakultet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guruh',
            name='fakultet',
        ),
        migrations.RemoveField(
            model_name='guruh',
            name='kurs',
        ),
        migrations.RemoveField(
            model_name='guruh',
            name='yonalish',
        ),
        migrations.RemoveField(
            model_name='kafedra',
            name='fakultet',
        ),
        migrations.RemoveField(
            model_name='kurs',
            name='fakultet',
        ),
        migrations.RemoveField(
            model_name='kurs',
            name='yonalish',
        ),
        migrations.RemoveField(
            model_name='yonalish',
            name='fakultet',
        ),
    ]
