# Generated by Django 4.2 on 2023-04-07 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talaba', '0010_remove_guruh_fakultet_remove_guruh_kurs_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fakultet',
        ),
        migrations.DeleteModel(
            name='Guruh',
        ),
        migrations.DeleteModel(
            name='Kafedra',
        ),
        migrations.DeleteModel(
            name='Kurs',
        ),
        migrations.DeleteModel(
            name='Yonalish',
        ),
    ]
