# Generated by Django 4.2 on 2023-04-08 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talaba', '0011_delete_fakultet_delete_guruh_delete_kafedra_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mfy',
            name='tuman',
        ),
        migrations.RemoveField(
            model_name='mfy',
            name='viloyat',
        ),
        migrations.RemoveField(
            model_name='tuman',
            name='viloyat',
        ),
    ]
