# Generated by Django 4.2 on 2023-05-02 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talaba', '0012_remove_mfy_tuman_remove_mfy_viloyat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talaba_activ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talaba_id', models.CharField(max_length=100)),
                ('activ', models.CharField(max_length=100)),
            ],
        ),
    ]
