# Generated by Django 4.1.6 on 2023-02-26 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yangiliklar',
            name='author',
        ),
        migrations.RemoveField(
            model_name='yangiliklar',
            name='summary',
        ),
    ]
