# Generated by Django 4.1.6 on 2023-02-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arm', '0002_remove_yangiliklar_author_remove_yangiliklar_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kitoblar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shifr', models.CharField(max_length=200)),
                ('aftor_belgisi', models.CharField(max_length=200)),
                ('invertor_nomeri', models.CharField(max_length=200)),
                ('mualiflar', models.CharField(max_length=200)),
                ('kitob_nomi', models.CharField(max_length=200)),
                ('nashriyot', models.CharField(max_length=200)),
                ('nashr_yili', models.CharField(max_length=200)),
                ('isbn', models.CharField(max_length=200)),
                ('kitob_narxi', models.CharField(max_length=200)),
                ('tili', models.CharField(choices=[('uz', 'uzbekcha'), ('ru', 'ruscha'), ('eng', 'ingilizcha'), ('boshqa', 'boshqa')], max_length=200)),
                ('alfabit', models.CharField(choices=[('lotin', 'lotin'), ('kiril', 'kiril'), ('boshqa', 'boshqa')], max_length=200)),
                ('darslik_turi', models.CharField(choices=[('darslik', 'darslik'), ('o`quv qo`llanma', 'o`quv qo`llanma'), ('uslubiy qo`llanma', 'uslubiy qo`llanma'), ('badiiy', 'badiiy'), ('siyosiy', 'siyosiy'), ('ilmiy', 'ilmiy'), ('lug`at', 'lug`at'), ('managrafiya', 'managrafiya')], max_length=200)),
                ('kitobni_fondagi_soni', models.CharField(max_length=200)),
                ('anatatsiya', models.TextField(max_length=600)),
                ('mundarija', models.CharField(max_length=600)),
                ('kitob_turi', models.CharField(choices=[('kitob', 'kitob'), ('elektron', 'elektron')], max_length=100)),
                ('kitob_rasmini_kiriting', models.ImageField(null=True, upload_to='rasm/')),
                ('fayl', models.FileField(blank=True, upload_to='kitob/')),
                ('sana', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
