# Generated by Django 4.1.6 on 2023-02-26 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arm', '0003_kitoblar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talaba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formulyar_raqami', models.CharField(max_length=200)),
                ('darajasi', models.CharField(max_length=200)),
                ('fakultet', models.CharField(max_length=100, verbose_name='Fakultet')),
                ('yonalish', models.CharField(max_length=100, verbose_name='Yo`nalish')),
                ('kurs', models.CharField(max_length=200)),
                ('guruh', models.CharField(max_length=100, verbose_name='Guruh')),
                ('familya', models.CharField(max_length=100, verbose_name='Familya')),
                ('ism', models.CharField(max_length=100, verbose_name='Ism')),
                ('sharifi', models.CharField(max_length=100, verbose_name='Sharif')),
                ('tugilgan_kun_oy_yil', models.CharField(max_length=100)),
                ('viloyat', models.CharField(max_length=100, verbose_name='Viloyat')),
                ('tuman', models.CharField(max_length=100, verbose_name='Tuman')),
                ('kocha_uy', models.CharField(max_length=200)),
                ('tel_raqami', models.CharField(max_length=200)),
                ('pasport_seryasi', models.CharField(max_length=200)),
                ('pasport_raqami', models.CharField(max_length=200)),
                ('sana', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
