# Generated by Django 4.1.6 on 2023-02-26 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arm', '0004_talaba'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Talaba',
            new_name='Talabalar',
        ),
    ]
