# Generated by Django 4.2 on 2023-04-11 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arm', '0007_bolim_toifa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitoblar',
            name='anatatsiya',
            field=models.CharField(max_length=600),
        ),
    ]
