# Generated by Django 4.2 on 2023-04-12 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arm', '0010_rename_tugilgan_kun_oy_yil_talabalar_invertor_nomeri_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yangiliklar',
            name='rasm',
            field=models.FileField(upload_to='yangiliklar/'),
        ),
    ]
