# Generated by Django 4.2 on 2023-04-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arm', '0011_alter_yangiliklar_rasm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yangiliklar',
            name='rasm',
            field=models.ImageField(upload_to='yangiliklar/'),
        ),
    ]
