# Generated by Django 4.2 on 2023-05-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arm', '0014_alter_kitoblar_mundarija'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alfabit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alfabit', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Resurs_sohasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resurs_sohasi', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Resurs_turi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resurs_turi', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tili',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tili', models.CharField(max_length=100)),
            ],
        ),
    ]
