# Generated by Django 4.2 on 2023-05-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arm', '0015_alfabit_resurs_sohasi_resurs_turi_tili'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitoblar',
            name='anatatsiya',
            field=models.CharField(max_length=10000),
        ),
    ]
