# Generated by Django 4.2 on 2023-04-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dekanat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lavozim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lavozim', models.CharField(max_length=100)),
                ('sana', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
